### ISSUE TITLE
Server crashed by user actions

### ISSUE THREAD

**Issue by TheBizzle** [NetLogo/Teletortoise#1]
_From @TheBizzle on January 11, 2014 16:40_

Here's the corresponding log:

> [info] 06:36:22.456 - application - Gabriel joining
> [info] 06:36:39.322 - application - "test/tortoise/Termites.nlogo" requested
> [info] 06:36:39.958 - application - Command(Gabriel,open,turtles-own [next steps]
> [info] 06:36:39.958 - application - Opening
> [info] 06:36:39.965 - application - Opening model
> [info] 06:36:40.382 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:40.383 - application - Compiling
> [info] 06:36:42.039 - application - Finished opening model
> [info] 06:36:49.801 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:49.802 - application - Compiling
> [info] 06:36:50.539 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:50.540 - application - Compiling
> [info] 06:36:52.073 - application - Command(Gabriel,compile,turtles-own [next steps]
> [info] 06:36:52.074 - application - Compiling
> [info] 06:39:56.826 - application - "test/benchmarks/CA1D%20Benchmark.nlogo" requested
> [info] 06:39:58.027 - application - Command(Gabriel,open,globals
> [info] 06:39:58.027 - application - Opening
> [info] 06:39:58.027 - application - Opening model
> [info] 06:40:00.177 - application - Command(Gabriel,compile,globals
> [info] 06:40:00.178 - application - Compiling
> [info] 06:45:47.738 - application - Finished opening model
> [info] 06:46:52.755 - application - Command(You,open,globals [grass]  ;; keep track of how much grass there is
> [info] 06:46:54.313 - application - Opening
> [info] 06:46:54.339 - application - Command(You,compile,globals [grass]  ;; keep track of how much grass there is
> [info] 06:46:55.441 - application - Beginning compilation
> [ERROR] [01/11/2014 06:46:58.986] [application-akka.actor.default-dispatcher-25] [akka://application/user/$E] Timed out
> akka.pattern.AskTimeoutException: Timed out
>         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
>         at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
>         at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:782)
>         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:779)
>         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
>         at java.lang.Thread.run(Thread.java:722)
> 
> [info] 06:47:08.779 - application - Compiling
> [info] 06:47:08.939 - application - Beginning compilation
> [info] 06:47:11.688 - application - Command(You,open,globals [
> [info] 06:47:11.711 - application - Command(You,compile,globals [
> [info] 06:47:11.689 - application - Opening
> [info] 06:47:11.886 - application - Beginning compilation
> [ERROR] [01/11/2014 06:47:11.690] [application-akka.actor.default-dispatcher-25] [akka://application/user/$E] Futures timed out after [1 second]
> java.util.concurrent.TimeoutException: Futures timed out after [1 second]
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:96)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:100)
>         at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
>         at scala.concurrent.Await$.result(package.scala:107)
>         at models.local.LocalInstance.compile(LocalInstance.scala:66)
>         at models.core.WebInstance$$anonfun$receiveBase$1.applyOrElse(WebInstance.scala:38)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:456)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> 
> [warn] 06:47:12.350 - application - Execution failed: Nothing named GRASS? has been defined
> [info] 06:47:12.355 - application - Compilation complete
> [INFO] [01/11/2014 06:47:12.442] [application-akka.actor.default-dispatcher-19] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$G#1677652596] to Actor[akka://application/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [info] 06:47:14.250 - application - Compiling
> [ERROR] [01/11/2014 06:47:14.249] [application-akka.actor.default-dispatcher-33] [akka://application/user/$H] Futures timed out after [1 second]
> java.util.concurrent.TimeoutException: Futures timed out after [1 second]
>         at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:96)
>         at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:100)
>         at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:107)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread$$anon$3.block(ThreadPoolBuilder.scala:169)
>         at scala.concurrent.forkjoin.ForkJoinPool.managedBlock(ForkJoinPool.java:3640)
>         at akka.dispatch.MonitorableThreadFactory$AkkaForkJoinWorkerThread.blockOn(ThreadPoolBuilder.scala:167)
>         at scala.concurrent.Await$.result(package.scala:107)
>         at models.local.LocalInstance.open(LocalInstance.scala:71)
>         at models.core.WebInstance$$anonfun$receiveBase$1.applyOrElse(WebInstance.scala:41)
>         at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:166)
>         at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
>         at akka.actor.ActorCell.invoke(ActorCell.scala:456)
>         at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
>         at akka.dispatch.Mailbox.run(Mailbox.scala:219)
>         at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
>         at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
>         at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
>         at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
>         at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
> 
> [info] 06:47:14.258 - application - Beginning compilation
> [ERROR] [01/11/2014 06:47:18.298] [application-akka.actor.default-dispatcher-25] [akka://application/user/$H] Timed out
> akka.pattern.AskTimeoutException: Timed out
>         at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:334)
>         at akka.actor.Scheduler$$anon$11.run(Scheduler.scala:118)
>         at scala.concurrent.Future$InternalCallbackExecutor$.scala$concurrent$Future$InternalCallbackExecutor$$unbatchedExecute(Future.scala:782)
>         at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:779)
>         at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(Scheduler.scala:455)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.executeBucket$1(Scheduler.scala:407)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.nextTick(Scheduler.scala:411)
>         at akka.actor.LightArrayRevolverScheduler$$anon$12.run(Scheduler.scala:363)
>         at java.lang.Thread.run(Thread.java:722)
> 
> [warn] 06:47:26.178 - application - Execution failed: Nothing named ALBEDO has been defined
> [info] 06:47:26.178 - application - Compilation complete
> [INFO] [01/11/2014 06:47:26.179] [application-akka.actor.default-dispatcher-19] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$K#-1950102775] to Actor[akka://application/deadLetters] was not delivered. [6] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [info] 06:47:56.218 - application - No errors!
> [info] 06:47:56.393 - application - Compilation complete
> [info] 06:47:56.342 - application - No errors!
> [info] 06:47:56.395 - application - Compilation complete
> [INFO] [01/11/2014 06:47:56.686] [application-akka.actor.default-dispatcher-20] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$F#1166017523] to Actor[akka://application/deadLetters] was not delivered. [7] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> [INFO] [01/11/2014 06:47:56.686] [application-akka.actor.default-dispatcher-20] [akka://application/deadLetters] Message [java.lang.String] from Actor[akka://application/user/$I#-2119155620] to Actor[akka://application/deadLetters] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
> Killed

_Copied from original issue: NetLogo/Galapagos#114_

**Comment by TheBizzle** [comment]
Another (possibly unrelated) incident:

```
[info] 22:13:10.986 - application - Daniela joining
[info] 22:13:21.335 - application - "test/benchmarks/CA1D%20Benchmark.nlogo" requested
[info] 22:13:21.615 - application - Command(Daniela,open,globals
[info] 22:13:21.616 - application - Opening
[info] 22:13:21.616 - application - Opening model
[info] 22:13:22.971 - application - Command(Daniela,compile,globals
[info] 22:13:22.971 - application - Compiling
[info] 22:13:24.211 - application - Finished opening model
[info] 22:13:47.116 - application - "Sample%20Models/Earth%20Science/Grand%20Canyon.nlogo" requested
Killed
```

**Comment by TheBizzle** [comment]
Another (possibly unrelated) incident:

> [info] 04:24:56.869 - application - vince joining
> [info] 04:25:05.331 - application - "test/benchmarks/Ants%20Benchmark.nlogo" requested
> [info] 04:25:06.067 - application - Command(vince,open,globals [result]
> [info] 04:25:06.068 - application - Opening
> [info] 04:25:06.068 - application - Opening model
> [info] 04:25:06.336 - application - Command(vince,compile,globals [result]
> [info] 04:25:06.336 - application - Compiling
> [info] 04:25:07.020 - application - Finished opening model
> [info] 04:25:39.703 - application - "test/benchmarks/Heatbugs%20Benchmark.nlogo" requested
> [info] 04:25:40.196 - application - Command(vince,open,globals [result]
> [info] 04:25:40.223 - application - Opening
> [info] 04:25:40.225 - application - Opening model
> [info] 04:25:40.733 - application - Command(vince,compile,globals [result]
> [info] 04:25:40.733 - application - Compiling
> [info] 04:25:41.398 - application - Finished opening model
> [info] 04:26:08.318 - application - "test/tortoise/Vants.nlogo" requested
> [info] 04:26:08.790 - application - Command(vince,open,;; workarounds:
> [info] 04:26:08.790 - application - Opening
> [info] 04:26:08.790 - application - Opening model
> [info] 04:26:09.193 - application - Finished opening model
> [info] 04:26:09.291 - application - Command(vince,compile,;; workarounds:
> [info] 04:26:09.292 - application - Compiling
> [info] 04:26:26.090 - application - "test/benchmarks/Team%20Benchmark.nlogo" requested
> [info] 04:26:26.822 - application - Command(vince,open,globals
> [info] 04:26:26.822 - application - Opening
> [info] 04:26:26.822 - application - Opening model
> [info] 04:26:27.088 - application - Command(vince,compile,globals
> [info] 04:26:27.089 - application - Compiling
> [info] 04:26:27.538 - application - Finished opening model
> [info] 04:26:38.161 - application - "test/benchmarks/BZ%20Benchmark.nlogo" requested
> [info] 04:26:39.241 - application - Command(vince,open,globals [result]
> [info] 04:26:39.268 - application - Opening
> [info] 04:26:39.270 - application - Opening model
> [info] 04:26:39.732 - application - Command(vince,compile,globals [result]
> [info] 04:26:39.739 - application - Compiling
> [info] 04:28:03.464 - application - Finished opening model
> [info] 04:28:08.865 - application - Command(vince,turtles,setup)
> [info] 04:28:10.037 - application - Executing (turtles, setup)
> [info] 04:28:11.792 - application - Completed (turtles, setup)
> [info] 04:28:43.860 - application - Command(vince,observer,setup)
> [info] 04:28:52.588 - application - Command(vince,observer,setup)
> [info] 04:28:54.026 - application - "test/tortoise/Vants.nlogo" requested
> [info] 04:29:08.934 - application - Command(vince,observer,setup)
> java.nio.channels.ClosedChannelException
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.cleanUpWriteBuffer(AbstractNioWorker.java:406)
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.close(AbstractNioWorker.java:374)
>         at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.handleAcceptedSocket(NioServerSocketPipelineSink.java:87)
>         at org.jboss.netty.channel.socket.nio.NioServerSocketPipelineSink.eventSunk(NioServerSocketPipelineSink.java:36)
>         at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
>         at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.handleDownstream(HttpPipeliningHandler.java:106)
>         at org.jboss.netty.channel.Channels.disconnect(Channels.java:781)
>         at org.jboss.netty.channel.AbstractChannel.disconnect(AbstractChannel.java:211)
>         at play.core.server.netty.WebSocketHandler$$anon$1.messageReceived(WebSocketHandler.scala:79)
>         at com.typesafe.netty.http.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:64)
>         at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:138)
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
>         at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
>         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
>         at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
>         at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
>         at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:109)
>         at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
>         at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:90)
>         at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
>         at java.lang.Thread.run(Thread.java:722)
> [info] 04:29:22.307 - application - Executing (observer, setup)
> [info] 04:29:22.307 - application - Executing (observer, setup)
> [info] 04:29:22.307 - application - Executing (observer, setup)
> [info] 04:30:00.257 - application - toto joining
> [info] 04:30:37.387 - application - "Sample%20Models/Biology/Wolf%20Sheep%20Predation.nlogo" requested
> [info] 04:30:41.011 - application - Command(toto,open,globals [grass]  ;; keep track of how much grass there is
> [info] 04:30:41.035 - application - Opening
> [info] 04:31:00.108 - application - Command(toto,compile,globals [grass]  ;; keep track of how much grass there is
> [info] 04:31:00.173 - application - Compiling
> [info] 04:31:02.600 - application - Command(toto,observer,setup)
> [info] 04:31:02.813 - application - Executing (observer, setup)
> Killed

**Comment by TheBizzle** [comment]
> [info] 08:04:14.515 - application - insi joining
> [info] 08:04:22.716 - application - "test/tortoise/Termites.nlogo" requested
> [info] 08:04:23.017 - application - Command(insi,open,turtles-own [next steps]
> [info] 08:04:23.018 - application - Opening
> [info] 08:04:23.018 - application - Opening model
> [info] 08:04:23.327 - application - Finished opening model
> [info] 08:04:23.523 - application - Command(insi,compile,turtles-own [next steps]
> [info] 08:04:23.523 - application - Compiling
> Killed
